### ISSUE TITLE
Add a line about actinia + basic exercises in the GRASS intro presentation

### ISSUE THREAD

**Issue by veroandreo** [veroandreo/grass_opengeohub2019#1]
We should add a line about actinia in the GRASS intro presentation with a link to your talk, too? What do you say @neteler? 

Also, since the blocks are of 2 hours, we could include some basic exercises for map displaying, region and mask setting, etc. I thought of something in the line of: https://gitpitch.com/veroandreo/grass-gis-conae/master?p=exercises/01_getting_familiar&grs=gitlab#/11 (move forward).

**Comment by neteler** [comment]
Yes, fully agreed!

**Comment by veroandreo** [comment]
Actinia part is ready

![image](https://user-images.githubusercontent.com/20075188/63021362-b4455c00-bea0-11e9-8024-1a730b1bd15a.png)

**Comment by neteler** [comment]
Super cool, thanks! :+1:

**Comment by veroandreo** [comment]
After the intro I added a link to the exercise here: https://neteler.gitlab.io/grass-gis-analysis/
