### ISSUE TITLE
Change shell loop to bash loop style

### ISSUE THREAD

**Issue by neteler** [veroandreo/grass_opengeohub2019#4]
For some users it might be better to avoid to avoid backticks:

https://github.com/veroandreo/grass_opengeohub2019/blob/bd6466d2fe85110ff53592cec952dedf871d7406/code/lst_time_series_code.sh#L350

suggestion:

`for MONTH in $(seq -w 1 12) ; do `

**Comment by veroandreo** [comment]
NDVI presentation still needs to be fixed accordingly

**Comment by veroandreo** [comment]
all grass code fixed as suggested
